budget/urls.py
from django.urls import path
from budget.views import (
    AdvisorList,
    ClientList,
    ExpenseList,
    IncomeList,
    BudgetList,
    AdvisorDetail,
    ClientDetail,
    ExpenseDetail,
    IncomeDetail,
    BudgetDetail,
    AdvisorCreate,
    ClientCreate,
    ExpenseCreate,
    IncomeCreate,
    BudgetCreate,
    BudgetCategoryCreate,
    AdvisorUpdate,
    ClientUpdate,
    ExpenseUpdate,
    IncomeUpdate,
    BudgetUpdate,
    BudgetCategoryUpdate,
    AdvisorDelete,
    ClientDelete,
    ExpenseDelete,
    IncomeDelete,
    BudgetDelete,
    BudgetCategoryDelete,
    FilterExpenseByCategory,
    FilterExpenseByFrequency,
    FilterIncomeByCategory,
    FilterIncomeByFrequency,
    VisualizeBudget
)

urlpatterns = [
    path('advisor/',
         AdvisorList.as_view(),
         name='budget_advisor_list_urlpattern'),

    path('advisor/<int:pk>/',
         AdvisorDetail.as_view(),
         name='budget_advisor_detail_urlpattern'),

    path('advisor/create/',
         AdvisorCreate.as_view(),
         name='budget_advisor_create_urlpattern'),

    path('advisor/<int:pk>/update/',
         AdvisorUpdate.as_view(),
         name='budget_advisor_update_urlpattern'),

    path('advisor/<int:pk>/delete/',
         AdvisorDelete.as_view(),
         name='budget_advisor_delete_urlpattern'),

    path('client/',
         ClientList.as_view(),
         name='budget_client_list_urlpattern'),

    path('client/<int:pk>/',
         ClientDetail.as_view(),
         name='budget_client_detail_urlpattern'),

    path('client/create/',
         ClientCreate.as_view(),
         name='budget_client_create_urlpattern'),

    path('client/<int:pk>/update/',
         ClientUpdate.as_view(),
         name='budget_client_update_urlpattern'),

    path('client/<int:pk>/delete/',
         ClientDelete.as_view(),
         name='budget_client_delete_urlpattern'),

    path('expense/',
         ExpenseList.as_view(),
         name='budget_expense_list_urlpattern'),

    path('expense/<int:pk>/',
         ExpenseDetail.as_view(),
         name='budget_expense_detail_urlpattern'),

    path('expense/create/',
         ExpenseCreate.as_view(),
         name='budget_expense_create_urlpattern'),

    path('expense/<int:pk>/update/',
         ExpenseUpdate.as_view(),
         name='budget_expense_update_urlpattern'),

    path('expense/<int:pk>/delete/',
         ExpenseDelete.as_view(),
         name='budget_expense_delete_urlpattern'),

    path('income/',
         IncomeList.as_view(),
         name='budget_income_list_urlpattern'),

    path('income/<int:pk>/',
         IncomeDetail.as_view(),
         name='budget_income_detail_urlpattern'),

    path('income/create/',
         IncomeCreate.as_view(),
         name='budget_income_create_urlpattern'),

    path('income/<int:pk>/update/',
         IncomeUpdate.as_view(),
         name='budget_income_update_urlpattern'),

    path('income/<int:pk>/delete/',
         IncomeDelete.as_view(),
         name='budget_income_delete_urlpattern'),

    path('budget/',
         BudgetList.as_view(),
         name='budget_budget_list_urlpattern'),

    path('budget/<int:pk>/',
         BudgetDetail.as_view(),
         name='budget_budget_detail_urlpattern'),

    path('budget/create/',
         BudgetCreate.as_view(),
         name='budget_budget_create_urlpattern'),

    path('budget/<int:pk>/update/',
         BudgetUpdate.as_view(),
         name='budget_budget_update_urlpattern'),

    path('budget/<int:pk>/delete/',
         BudgetDelete.as_view(),
         name='budget_budget_delete_urlpattern'),

    path('budgetcategory/create/',
         BudgetCategoryCreate.as_view(),
         name='budget_budget_category_create_urlpattern'),

    path('budgetcategory/<int:pk>/update/',
         BudgetCategoryUpdate.as_view(),
         name='budget_budget_category_update_urlpattern'),

    path('budgetcategory/<int:pk>/delete/',
         BudgetCategoryDelete.as_view(),
         name='budget_budget_category_delete_urlpattern'),

    path('expense/filter/category/',
         FilterExpenseByCategory.as_view(),
         name='budget_filter_expense_by_category_urlpattern'),

    path('expense/filter/frequency/',
         FilterExpenseByFrequency.as_view(),
         name='budget_filter_expense_by_frequency_urlpattern'),

    path('income/filter/category/',
         FilterIncomeByCategory.as_view(),
         name='budget_filter_income_by_category_urlpattern'),

    path('income/filter/frequency/',
         FilterIncomeByFrequency.as_view(),
         name='budget_filter_income_by_frequency_urlpattern'),

    path('budget/<int:pk>/visualize/',
         VisualizeBudget.as_view(),
         name='budget_budget_visualize_urlpattern'),

]

chen_evan_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(
             pattern_name='home_urlpattern',
             permanent=False
         )),

    path('home/',
         TemplateView.as_view(template_name='budget/home.html'),
         name='home_urlpattern'),

    path('about/',
         TemplateView.as_view(template_name='budget/about.html'),
         name='about_urlpattern'),

    path('login/',
         LoginView.as_view(template_name='budget/login.html'),
         name='login_urlpattern'),

    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'),

    path('admin/', admin.site.urls),

    path('', include('budget.urls'))
]

budget/models.py
from django.db import models
from django.urls import reverse


class Advisor(models.Model):
    advisor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('budget_advisor_detail_urlpattern', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('budget_advisor_update_urlpattern', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('budget_advisor_delete_urlpattern', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Financial Advisor"
        verbose_name_plural = "Financial Advisors"
        ordering = ['last_name', 'first_name']


class Client(models.Model):
    client_id = models.AutoField(primary_key=True)
    advisor = models.ForeignKey(Advisor, related_name='clients', on_delete=models.PROTECT)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('budget_client_detail_urlpattern', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('budget_client_update_urlpattern', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('budget_client_delete_urlpattern', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Client"
        verbose_name_plural = "Clients"
        ordering = ['last_name', 'first_name']


class ExpenseCategory(models.Model):
    expense_category_id = models.AutoField(primary_key=True)
    expense_category_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s' % self.expense_category_name

    class Meta:
        verbose_name = "Expense Category"
        verbose_name_plural = "Expense Categories"


class IncomeCategory(models.Model):
    income_category_id = models.AutoField(primary_key=True)
    income_category_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s' % self.income_category_name

    class Meta:
        verbose_name = "Income Category"
        verbose_name_plural = "Income Categories"


class Frequency(models.Model):
    frequency_id = models.AutoField(primary_key=True)
    frequency_name = models.CharField(max_length=20)

    def __str__(self):
        return '%s' % self.frequency_name

    class Meta:
        verbose_name = "Frequency"
        verbose_name_plural = "Frequencies"


class Expense(models.Model):
    expense_id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, related_name='expenses', on_delete=models.PROTECT)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=255)
    date = models.DateField()
    frequency = models.ForeignKey(Frequency, related_name='expenses', on_delete=models.PROTECT)
    category = models.ForeignKey(ExpenseCategory, related_name='expenses', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - $%s (%s, %s)' % (self.client, self.amount, self.category, self.frequency)

    def get_absolute_url(self):
        return reverse('budget_expense_detail_urlpattern', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('budget_expense_update_urlpattern', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('budget_expense_delete_urlpattern', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Expense"
        verbose_name_plural = "Expenses"
        ordering = ['date']


class Income(models.Model):
    income_id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, related_name='incomes', on_delete=models.PROTECT)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=255)
    date = models.DateField()
    frequency = models.ForeignKey(Frequency, related_name='incomes', on_delete=models.PROTECT)
    category = models.ForeignKey(IncomeCategory, related_name='incomes', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - $%s (%s, %s)' % (self.client, self.amount, self.category, self.frequency)

    def get_absolute_url(self):
        return reverse('budget_income_detail_urlpattern', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('budget_income_update_urlpattern', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('budget_income_delete_urlpattern', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Income"
        verbose_name_plural = "Incomes"
        ordering = ['date']


class Budget(models.Model):
    budget_id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, related_name='budgets', on_delete=models.PROTECT)
    start_date = models.DateField()
    end_date = models.DateField()
    budget_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.client, self.budget_name)

    def get_absolute_url(self):
        return reverse('budget_budget_detail_urlpattern', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('budget_budget_update_urlpattern', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('budget_budget_delete_urlpattern', kwargs={'pk': self.pk})

    def get_visualize_url(self):
        return reverse('budget_budget_visualize_urlpattern', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Budget"
        verbose_name_plural = "Budgets"
        ordering = ['start_date']


class BudgetCategory(models.Model):
    budget_category_id = models.AutoField(primary_key=True)
    budget = models.ForeignKey(Budget, related_name='budget_categories', on_delete=models.CASCADE)
    # We will assume budgets only manage expenses
    category = models.ForeignKey(ExpenseCategory, related_name='budget_categories', on_delete=models.PROTECT)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return '%s - %s: $%s' % (self.budget, self.category, self.amount)

    def get_update_url(self):
        return reverse('budget_budget_category_update_urlpattern', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('budget_budget_category_delete_urlpattern', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Budget Category"
        verbose_name_plural = "Budget Categories"
        ordering = ['category__expense_category_name']

budget/forms.py
from django import forms

from budget.models import (
    Advisor,
    Client,
    Expense,
    Income,
    Budget,
    BudgetCategory
)


class AdvisorForm(forms.ModelForm):
    class Meta:
        model = Advisor
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()


class ExpenseCreateForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'

    def clean_description(self):
        return self.cleaned_data['description'].strip()


class ExpenseUpdateForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['amount', 'description', 'frequency', 'date']

    def clean_description(self):
        return self.cleaned_data['description'].strip()


class IncomeCreateForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = '__all__'

    def clean_description(self):
        return self.cleaned_data['description'].strip()


class IncomeUpdateForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ['amount', 'description', 'frequency', 'date']

    def clean_description(self):
        return self.cleaned_data['description'].strip()


class BudgetForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = '__all__'

    def clean_budget_name(self):
        return self.cleaned_data['budget_name'].strip()


class BudgetCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = BudgetCategory
        fields = ['category', 'amount', 'budget']

    def __init__(self, *args, **kwargs):
        budget_id = kwargs.pop('budget_id', None)
        super().__init__(*args, **kwargs)
        self.fields['budget'].widget = forms.HiddenInput()  # hide budget selection from user

        if budget_id:
            self.fields['budget'].initial = budget_id


class BudgetCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = BudgetCategory
        fields = ['category', 'amount', 'budget']

    def __init__(self, *args, **kwargs):
        budget_id = kwargs.pop('budget_id', None)
        super().__init__(*args, **kwargs)
        self.fields['budget'].widget = forms.HiddenInput()  # hide budget selection from user
        self.fields['category'].widget = forms.HiddenInput()  # hide category selection from user

        if budget_id:
            self.fields['budget'].initial = budget_id

budget/templates/budget/advisor_confirm_delete.html
{% extends 'budget/base.html' %}

{% block title %}
    Delete Advisor
{% endblock %}

{% block heading %}
    <h1>Delete Advisor</h1>
{% endblock %}

{% block content %}
    <form
        action="{{ advisor.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p class="notice">
            Are you sure that you want to delete
            advisor <b>{{ advisor }}</b>?
        </p>
        <a href="{{ advisor.get_absolute_url }}" class="button">Cancel</a>
        <button type="submit">Delete Advisor</button>
    </form>
{% endblock %}

budget/templates/budget/advisor_form.html
{% extends 'budget/base.html' %}

{% block title %}
    Create Advisor
{% endblock %}

{% block heading %}
    <h1>Create Advisor</h1>
{% endblock %}

{% block content %}
    <form
        action="{% url 'budget_advisor_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Advisor</button>
    </form>
{% endblock %}

budget/templates/budget/advisor_list.html
{% extends 'budget/base.html' %}
{% block title %}
    Advisor List
{% endblock %}

{% block heading %}
    <h1>Advisors</h1>
{% endblock %}

{% block content %}
    {% if perms.budget.add_advisor %}
        <a class="button" href="{% url 'budget_advisor_create_urlpattern' %}">Create New Advisor</a>
    {% endif %}

    <ul>
        {% for advisor in advisor_list %}
            <li><a href="{{ advisor.get_absolute_url }}">{{ advisor }}</a></li>
        {% empty %}
            <li><em>There are currently no advisors available.</em></li>
        {% endfor %}
    </ul>

{% endblock %}

budget/templates/budget/budget_detail.html
{% extends 'budget/base.html' %}
{% block title %}
    Budget Detail
{% endblock %}

{% block heading %}
    <h1>Budget - {{ budget }}</h1>
{% endblock %}

{% block content %}
    <section>
        <h3>Budget Information</h3>
        {% if perms.budget.view_budget %}
            <a class="button" href="{{ budget.get_visualize_url }}">Visualize Budget</a>
        {% endif %}

        <table>
            <tr>
                <td>Client:</td>
                <td><a href="{{ budget.client.get_absolute_url }}">{{ budget.client }}</a></td>
            </tr>
            <tr>
                <td>Budget Name:</td>
                <td>{{ budget.budget_name }}</td>
            </tr>
            <tr>
                <td>Start Date:</td>
                <td>{{ budget.start_date }}</td>
            </tr>
            <tr>
                <td>End Date:</td>
                <td>{{ budget.end_date }}</td>
            </tr>
        </table>
        <div>
            {% if perms.budget.change_budget %}
                <a class="button" href="{{ budget.get_update_url }}">Update Budget</a>
            {% endif %}
            {% if perms.budget.delete_budget %}
            <a class="button" href="{{ budget.get_delete_url }}">Delete Budget</a>
            {% endif %}
        </div>
    </section>
    <section>
        <h3>Categories</h3>
        {% if perms.budget.add_budgetcategory %}
            <a class="button" href="{% url 'budget_budget_category_create_urlpattern' %}?budget_id={{ budget.pk }}">Create Category</a>
        {% endif %}
        <ul>
            {% for category in budget_categories %}
                <li>
                    {{ category.category }}: ${{ category.amount }} &emsp;
                    {% if perms.budget.change_budgetcategory %}
                        <a href="{{ category.get_update_url }}?budget_id={{ budget.pk }}">Update Category</a> &emsp;
                    {% endif %}
                    {% if perms.budget.delete_budgetcategory %}
                        <a href="{{ category.get_delete_url }}?budget_id={{ budget.pk }}">Delete Category</a>
                    {% endif %}
                </li>
            {% empty %}
                <li><em>There are currently no categories under this budget.</em></li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

budget/templates/budget/budget_form.html
{% extends 'budget/base.html' %}

{% block title %}
    Create Budget
{% endblock %}

{% block heading %}
    <h1>Create Budget</h1>
{% endblock %}

{% block content %}
    <form
        action="{% url 'budget_budget_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Budget</button>
    </form>
{% endblock %}

budget/templates/budget/budget_form_update.html
{% extends 'budget/base.html' %}

{% block title %}
    Update Budget
{% endblock %}

{% block heading %}
    <h1>Update Budget - {{ budget }}</h1>
{% endblock %}

{% block content %}
    <form
        action="{{ budget.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Budget</button>
    </form>
{% endblock %}

budget/templates/budget/budgetcategory_form_update.html
{% extends 'budget/base.html' %}

{% block title %}
    Update Budget Category
{% endblock %}

{% block heading %}
    <h1>Update Budget Category</h1>
{% endblock %}

{% block content %}
    <form
        action="{{ budgetcategory.get_update_url }}"
        method="post">
        {% csrf_token %}
        <p class="notice">
            This budget category is for budget <b>{{ budget }}</b>,
            under the category <b>{{ budgetcategory.category }}</b>.
        </p>
        {{ form.as_p }}
        <button type="submit">Update Budget Category</button>
    </form>
{% endblock %}

budget/templates/budget/client_detail.html
{% extends 'budget/base.html' %}
{% block title %}
    Client Detail
{% endblock %}

{% block heading %}
    <h1>Client - {{ client }}</h1>
{% endblock %}

{% block content %}
    <section>
        <h3>Client Information</h3>
        <table>
            <tr>
                <td>First Name:</td>
                <td>{{ client.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name:</td>
                <td>{{ client.last_name }}</td>
            </tr>
            <tr>
                <td>Advisor:</td>
                <td>{{ client.advisor }}</td>
            </tr>
        </table>
        <div>
            {% if perms.budget.change_client %}
                <a class="button" href="{{ client.get_update_url }}">Update Client</a>
            {% endif %}
            {% if perms.budget.delete_client %}
                <a class="button" href="{{ client.get_delete_url }}">Delete Client</a>
            {% endif %}
        </div>
    </section>
    <section>
        <h3>Expenses</h3>
        <ul>
            {% for expense in expense_list %}
                <li><a href="{{ expense.get_absolute_url }}">{{ expense }}</a></li>
            {% empty %}
                <li><em>There are currently no expenses associated with this client.</em></li>
            {% endfor %}
        </ul>
        <h3>Incomes</h3>
        <ul>
            {% for income in income_list %}
                <li><a href="{{ income.get_absolute_url }}">{{ income }}</a></li>
            {% empty %}
                <li><em>There are currently no incomes associated with this client.</em></li>
            {% endfor %}
        </ul>
        <h3>Budgets</h3>
            <ul>
            {% for budget in budget_list %}
                <li><a href="{{ budget.get_absolute_url }}">{{ budget }}</a></li>
            {% empty %}
                <li><em>There are currently no budgets associated with this client.</em></li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

budget/templates/budget/expense_form.html
{% extends 'budget/base.html' %}

{% block title %}
    Create Expense
{% endblock %}

{% block heading %}
    <h1>Create Expense</h1>
{% endblock %}

{% block content %}
    <form
        action="{% url 'budget_expense_create_urlpattern'%}"
        method="post">
        <aside>
            <p><b>Note:</b></p>
            <p>The expected input format for <code>Date</code> is <br> 'YYYY-MM-DD'</p>
        </aside>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Expense</button>
    </form>
{% endblock %}

budget/templates/budget/filter_income_by_category.html
{% extends 'budget/base.html' %}
{% block title %}
    Filter Incomes by Category
{% endblock %}

{% block heading %}
    <h1>Filter Incomes by Category</h1>
{% endblock %}

{% block content %}
<form method="get" action="">
    {% if not selected_category %}
        <aside>
            <p><i>*Note: no filter applied, all incomes shown.</i></p>
        </aside>
    {% endif %}
    <label>
        <select name="income_category_id">
            {% if selected_category %}
                <option value="{{ selected_category.income_category_id }}">{{ selected_category.income_category_name }}</option>
            {% endif %}
            <option value="">All Income Categories</option>
            {% for category in categories %}
                <option value="{{ category.income_category_id }}">{{ category.income_category_name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
    </label>
</form>

<ul>
    {% for income in incomes %}
        <li><a href="{{ income.get_absolute_url }}">{{ income }}</a></li>
    {% empty %}
        <li><em>There are currently no incomes in the {{ selected_category }} category.</em></li>
    {% endfor %}
</ul>

<br>

<div style="justify-content: space-between; display: flex">
    <a class="button" href="{% url 'budget_income_list_urlpattern' %}">Back to Income List</a>
    <a class="button" href="{% url 'budget_income_create_urlpattern' %}">Create New Income</a>
</div>
{% endblock %}

budget/templates/budget/filter_income_by_frequency.html
{% extends 'budget/base.html' %}
{% block title %}
    Filter Incomes by Frequency
{% endblock %}

{% block heading %}
    <h1>Filter Incomes by Frequency</h1>
{% endblock %}

{% block content %}
<form method="get" action="">
    {% if not selected_frequency %}
        <aside>
            <p><i>*Note: no filter applied, all incomes shown.</i></p>
        </aside>
    {% endif %}
    <label>
        <select name="income_frequency_id">
            {% if selected_frequency %}
                <option value="{{ selected_frequency.frequency_id }}">{{ selected_frequency.frequency_name }}</option>
            {% endif %}
            <option value="">All Frequencies</option>
            {% for frequency in frequencies %}
                <option value="{{ frequency.frequency_id }}">{{ frequency.frequency_name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
    </label>
</form>

<ul>
    {% for income in incomes %}
        <li><a href="{{ income.get_absolute_url }}">{{ income }}</a></li>
    {% empty %}
        <li><em>There are currently no incomes occurring at {{ selected_frequency }} frequency.</em></li>
    {% endfor %}
</ul>

<br>

<div style="justify-content: space-between; display: flex">
    <a class="button" href="{% url 'budget_income_list_urlpattern' %}">Back to Income List</a>
    <a class="button" href="{% url 'budget_income_create_urlpattern' %}">Create New Income</a>
</div>
{% endblock %}

budget/templates/budget/income_form_update.html
{% extends 'budget/base.html' %}

{% block title %}
    Update Income
{% endblock %}

{% block heading %}
    <h1>Update Income - {{ client }} ({{ category }})</h1>
{% endblock %}

{% block content %}
    <form
        action="{{ income.get_update_url }}"
        method="post">
        <aside>
            <p><b>Note:</b></p>
            <p>The expected input format for <code>Date</code> is <br> 'YYYY-MM-DD'</p>
        </aside>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Income</button>
    </form>
{% endblock %}

budget/templates/budget/income_list.html
{% extends 'budget/base.html' %}
{% block title %}
    Income List
{% endblock %}

{% block heading %}
    <h1>Incomes</h1>
{% endblock %}

{% block content %}
    {% if perms.budget.add_income %}
        <a class="button" href="{% url 'budget_income_create_urlpattern' %}">Create New Income</a>
    {% endif %}
    {% if perms.budget.view_income %}
        <a class="button" href="{% url 'budget_filter_income_by_category_urlpattern' %}">Filter By Category</a>
    {% endif %}
    {% if perms.budget.view_income %}
        <a class="button" href="{% url 'budget_filter_income_by_frequency_urlpattern' %}">Filter By Frequency</a>
    {% endif %}

    <ul>
        {% for income in income_list %}
            <li><a href="{{ income.get_absolute_url }}">{{ income }}</a></li>
        {% empty %}
            <li><em>There are currently no incomes available.</em></li>
        {% endfor %}
    </ul>

{% endblock %}

budget/templates/budget/login.html
{% extends 'budget/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block heading %}
    <h1>Login</h1>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}